CREATE TABLE RH_USER
(
    USER_ID  VARCHAR2(36 CHAR)  NOT NULL,
    NAME     VARCHAR2(100 CHAR) NOT NULL,
    EMAIL    VARCHAR2(150 CHAR) NOT NULL,
    PASSWORD VARCHAR2(100 CHAR) NOT NULL,
    USERNAME VARCHAR2(16 CHAR)  NOT NULL,

    CONSTRAINT PK_RH_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_RH_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_RH_USER_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE RH_USER IS 'Tabela para armazenar os usuários do sistema';

COMMENT ON COLUMN RH_USER.USER_ID IS 'Identificador unico do usuário';
COMMENT ON COLUMN RH_USER.NAME IS 'Nome do usuário';
COMMENT ON COLUMN RH_USER.EMAIL IS 'Email do usuário';
COMMENT ON COLUMN RH_USER.PASSWORD IS 'Hash da senha do usuário';
COMMENT ON COLUMN RH_USER.USERNAME IS 'Username unico para acesso do usuário';
