CREATE TABLE RH_PASSWORD_RECOVER
(
    USER_ID         RAW(16)   NOT NULL,
    RECOVER_CODE    RAW(16)   NOT NULL,
    EXPIRATION_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_RH_PASSWORD_RECOVER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_RH_PASSWORD_RECOVER_RECOVER_CODE UNIQUE (RECOVER_CODE),
    CONSTRAINT FK_RH_PASSWORD_RECOVER_USER FOREIGN KEY (USER_ID) REFERENCES RH_USER (USER_ID)
);


COMMENT ON TABLE RH_PASSWORD_RECOVER IS 'Tabela para armazenar os códigos de recuperação de senha dos usuários';

COMMENT ON COLUMN RH_PASSWORD_RECOVER.USER_ID IS 'Identificador do usuário que solicitou a recuperação de senha';

COMMENT ON COLUMN RH_PASSWORD_RECOVER.RECOVER_CODE IS 'Código de recuperação gerado para o usuário';

COMMENT ON COLUMN RH_PASSWORD_RECOVER.EXPIRATION_DATE IS 'Data de expiração do código de recuperação';
