spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: RH_SYSTEM
    password: RH_SYSTEM
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    locations: classpath:db/migration/oracle
    baseline-on-migrate: true