spring:
  application:
    name: rhsystemapi
  datasource:
    url: jdbc:postgresql://localhost:5432/rhsystem
    username: rhsystem
    password: rhsystem
    hikari:
      pool-name: RhSystemPoll
      minimum-idle: 10
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 20000
  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: joaohenriquetdj@gmail.com
    password: liduwtmfyjsqeron
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
