CREATE TABLE RH_USER (
    USER_ID UUID NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    PASSWORD TEXT NOT NULL,
    USERNAME VARCHAR(10),
    CONSTRAINT PK_RH_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_RH_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_RH_USER_USERNAME UNIQUE (USERNAME)
);

COMMENT ON TABLE RH_USER IS 'Tabela para armasenar os usuarios';

COMMENT ON COLUMN RH_USER.USER_ID IS 'Identificador do usuário';

COMMENT ON COLUMN RH_USER.NAME IS 'Nome do usuário';

COMMENT ON COLUMN RH_USER.EMAIL IS 'Identificador do usuário';

COMMENT ON COLUMN RH_USER.PASSWORD IS 'Hash da senha do usuário';

COMMENT ON COLUMN RH_USER.USERNAME IS 'Nome de acesso do usuario';

COMMENT ON CONSTRAINT PK_RH_USER ON RH_USER IS 'Chave primária da tabela RH_USER';

COMMENT ON CONSTRAINT UK_RH_USER_EMAIL ON RH_USER IS 'Restrição de unicidade para o email do usuário';

COMMENT ON CONSTRAINT UK_RH_USER_USERNAME ON RH_USER IS 'Restrição de unicidade para o nome de usuário';