name: build.yml
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & Test (verbose)
        run: |
          mvn -B -U \
            -Dsurefire.printSummary=true \
            -Dsurefire.useFile=false \
            -DtrimStackTrace=false \
            -DfailIfNoTests=false \
            verify || echo "MVN_EXIT=$?" >> mvn_exit.txt

      - name: Print surefire reports (if fail)
        if: failure()
        run: |
          echo "==== LIST FILES ===="
            ls -1 target/surefire-reports || true
          echo "==== REPORTS ===="
            for f in target/surefire-reports/*.txt; do
              echo "----- $f -----"
              cat "$f"
            done || true
            for f in target/surefire-reports/*.dumpstream; do
              echo "----- $f -----"
              cat "$f"
            done || true

      - name: Upload surefire artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports
            mvn_exit.txt
          if-no-files-found: warn
