name: Finish Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  finish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java and Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Detect release branch
        id: detect_branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Get version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Final version (no SNAPSHOT): $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch main
        run: |
          git fetch origin main:main

      - name: Try merging release into main
        id: merge
        continue-on-error: true
        run: |
          git checkout main
          git merge --no-ff origin/${{ steps.detect_branch.outputs.branch }} -m "Merge release ${{ steps.version.outputs.version }}"

      - name: Push to main and create tag
        if: steps.merge.outcome == 'success'
        run: |
          git push origin main
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Create Pull Request if conflict
        if: steps.merge.outcome != 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ steps.detect_branch.outputs.branch }}
          title: "Finalize release ${{ steps.version.outputs.version }}"
          body: |
            ⚠️ Conflitos ao tentar mesclar `${{ steps.detect_branch.outputs.branch }}` em `main`.
            Esta PR foi aberta automaticamente para revisão.
          draft: false
